# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: drl.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'drl.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import gpa_pb2 as gpa__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\tdrl.proto\x1a\tgpa.proto\"?\n\nDRLRequest\x12\x1e\n\nstudent_id\x18\x01 \x01(\x0b\x32\n.StudentId\x12\x11\n\tdrl_score\x18\x02 \x01(\x02\" \n\x0b\x44RLResponse\x12\x11\n\tdrl_score\x18\x01 \x01(\x02\x32T\n\x03\x44RL\x12\'\n\x0bGetDRLScore\x12\n.StudentId\x1a\x0c.DRLResponse\x12$\n\x0e\x43reateDRLScore\x12\x0b.DRLRequest\x1a\x05.VoidB\x12\n\x10io.grpc.examplesb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'drl_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\020io.grpc.examples'
  _globals['_DRLREQUEST']._serialized_start=24
  _globals['_DRLREQUEST']._serialized_end=87
  _globals['_DRLRESPONSE']._serialized_start=89
  _globals['_DRLRESPONSE']._serialized_end=121
  _globals['_DRL']._serialized_start=123
  _globals['_DRL']._serialized_end=207
# @@protoc_insertion_point(module_scope)
