# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import drl_pb2 as drl__pb2
import gpa_pb2 as gpa__pb2

GRPC_GENERATED_VERSION = '1.75.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in drl_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class DRLStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetDRLScore = channel.unary_unary(
                '/DRL/GetDRLScore',
                request_serializer=gpa__pb2.StudentId.SerializeToString,
                response_deserializer=drl__pb2.DRLResponse.FromString,
                _registered_method=True)
        self.CreateDRLScore = channel.unary_unary(
                '/DRL/CreateDRLScore',
                request_serializer=drl__pb2.DRLRequest.SerializeToString,
                response_deserializer=gpa__pb2.Void.FromString,
                _registered_method=True)


class DRLServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetDRLScore(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateDRLScore(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_DRLServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetDRLScore': grpc.unary_unary_rpc_method_handler(
                    servicer.GetDRLScore,
                    request_deserializer=gpa__pb2.StudentId.FromString,
                    response_serializer=drl__pb2.DRLResponse.SerializeToString,
            ),
            'CreateDRLScore': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateDRLScore,
                    request_deserializer=drl__pb2.DRLRequest.FromString,
                    response_serializer=gpa__pb2.Void.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'DRL', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('DRL', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class DRL(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetDRLScore(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/DRL/GetDRLScore',
            gpa__pb2.StudentId.SerializeToString,
            drl__pb2.DRLResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateDRLScore(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/DRL/CreateDRLScore',
            drl__pb2.DRLRequest.SerializeToString,
            gpa__pb2.Void.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
