# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import gpa_pb2 as gpa__pb2

GRPC_GENERATED_VERSION = '1.75.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in gpa_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class GPAStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetGPA = channel.unary_unary(
                '/GPA/GetGPA',
                request_serializer=gpa__pb2.StudentId.SerializeToString,
                response_deserializer=gpa__pb2.GPAResponse.FromString,
                _registered_method=True)
        self.CreateGPA = channel.unary_unary(
                '/GPA/CreateGPA',
                request_serializer=gpa__pb2.GPARequest.SerializeToString,
                response_deserializer=gpa__pb2.Void.FromString,
                _registered_method=True)


class GPAServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetGPA(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateGPA(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_GPAServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetGPA': grpc.unary_unary_rpc_method_handler(
                    servicer.GetGPA,
                    request_deserializer=gpa__pb2.StudentId.FromString,
                    response_serializer=gpa__pb2.GPAResponse.SerializeToString,
            ),
            'CreateGPA': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateGPA,
                    request_deserializer=gpa__pb2.GPARequest.FromString,
                    response_serializer=gpa__pb2.Void.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'GPA', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('GPA', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class GPA(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetGPA(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/GPA/GetGPA',
            gpa__pb2.StudentId.SerializeToString,
            gpa__pb2.GPAResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateGPA(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/GPA/CreateGPA',
            gpa__pb2.GPARequest.SerializeToString,
            gpa__pb2.Void.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
