# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: gpa.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'gpa.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\tgpa.proto\"\x06\n\x04Void\"\x17\n\tStudentId\x12\n\n\x02id\x18\x01 \x01(\x03\" \n\x0bGPAResponse\x12\x11\n\tgpa_score\x18\x01 \x01(\x02\"?\n\nGPARequest\x12\x1e\n\nstudent_id\x18\x01 \x01(\x0b\x32\n.StudentId\x12\x11\n\tgpa_score\x18\x02 \x01(\x02\x32J\n\x03GPA\x12\"\n\x06GetGPA\x12\n.StudentId\x1a\x0c.GPAResponse\x12\x1f\n\tCreateGPA\x12\x0b.GPARequest\x1a\x05.VoidB\x12\n\x10io.grpc.examplesb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'gpa_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\020io.grpc.examples'
  _globals['_VOID']._serialized_start=13
  _globals['_VOID']._serialized_end=19
  _globals['_STUDENTID']._serialized_start=21
  _globals['_STUDENTID']._serialized_end=44
  _globals['_GPARESPONSE']._serialized_start=46
  _globals['_GPARESPONSE']._serialized_end=78
  _globals['_GPAREQUEST']._serialized_start=80
  _globals['_GPAREQUEST']._serialized_end=143
  _globals['_GPA']._serialized_start=145
  _globals['_GPA']._serialized_end=219
# @@protoc_insertion_point(module_scope)
